# Generated by Django 5.0.6 on 2024-05-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salle', models.CharField(max_length=10)),
                ('numero_etage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('date_achat', models.DateField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type_budget', models.CharField(max_length=100)),
                ('accessoires', models.CharField(max_length=200)),
                ('etat_accessoires', models.CharField(max_length=200)),
                ('detenteur_actuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_detenus', to='gestion_materiel.enseignant')),
                ('proprietaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_possedes', to='gestion_materiel.enseignant')),
                ('salle_actuelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_stockes', to='gestion_materiel.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pret', models.DateField()),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('lieu_pret', models.CharField(max_length=100)),
                ('objectif_utilisation', models.CharField(max_length=200)),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='gestion_materiel.enseignant')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_materiel.equipement')),
            ],
        ),
    ]
