# Generated by Django 5.0.6 on 2024-05-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_materiel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pret',
            name='lieu_pret',
        ),
        migrations.AddField(
            model_name='equipement',
            name='acheteur',
            field=models.CharField(choices=[('lycee', 'Lycée'), ('mandant', 'Mandant')], default='lycee', max_length=100),
        ),
    ]
