# Generated by Django 5.0.6 on 2024-06-02 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_materiel', '0002_remove_pret_lieu_pret_equipement_acheteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='lieu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_materiel.salle'),
        ),
    ]
